ecmwf/eccodes

- README
> Minor text

- CMakeLists.txt
- cmake/eccodes_find_linux_utils.cmake
Now the checks should actually run ;)
> ECC-852 - fixups to PR #4

- .appveyor.yml
- CMakeLists.txt
- cmake/eccodes_find_linux_utils.cmake
Third time lucky.
The CI tests need to be set as required so dodgy build-breaking changes can't be merged :)
> ECC-852: Fix the build

- .github/workflows/ci.yml
- .github/workflows/label-public-pr.yml
- .github/workflows/reusable-ci-hpc.yml
- .github/workflows/reusable-ci.yml
Trigger public and private part of downstream CI on self-hosted runners and the HPC.
> Enable downstream CI

- definitions/grib2/tables/local/ecmf/1/4.0.table
- definitions/grib2/template.4.65533.def
- definitions/grib2/template.4.65534.def
- definitions/grib2/template.4.leps.def
adding new local templates for large ensembles
> large ensembles

- .github/workflows/ci.yml
- .github/workflows/reusable-ci.yml
Add a job to generate code coverage report.
> Add code coverage CI job

- definitions/mars/grib.ocda.tpa.def
- definitions/mars/grib.oper.fc.def
minor changes to MARS keywords mapping for ocean data
> adding stepRange for ocean data

- definitions/grib2/typeOfLevelConcept.def
Add few typeOfLevel to GRIB2 definitions, see following page:
https://codes.ecmwf.int/grib/format/grib2/ctables/4/5/
> Add few typeOfLevel to GRIB2 definitions

- .github/workflows/ci.yml
> Prevent failure of CI notification for PRs from forks

- definitions/mars/class.table
Please merge this feature/marskeys4hydro branch into the develop branch.
> ECC-1736: MARS classes for C3S hydrology and CERISE projects

- definitions/grib2/section.4.def
- definitions/mars/grib.mmsf.fc.def
- definitions/mars/grib.msmm.fcmean.def
https://jira.ecmwf.int/browse/ECC-1756
> ECC-1756: Feature/cerise configs

- src/grib_context.cc
The field grib_samples_path from grib_context was being left in an inconsistent state, either with static memory or with heap allocated memory, depending on the existence of the env var ECCODES_SAMPLES_PATH and the preprocessor variable ECCODES_SAMPLES_PATH.
Free the memory allocated for grib_samples_path and grib_definition_files_path when setting them from the API calls.
> Fix memory leaks

- definitions/grib2/destine_activity.table
- definitions/grib2/destine_experiment.table
Added the following entry to "grib2/destine_activity.table":
- 4 story-nudging Climate storylines by nudging to reanalysis
Added the following entry to "grib2/destine_experiment.table":
- 9 Tplus1.5K Warmer world at 1.5 degrees above pre-industrial temperatures
- 10 Tplus2.0K Warmer world at 2 degrees K above pre-industrial temperatures
- 11 Tplus3.0K Warmer world at 3 degrees K above pre-industrial temperatures
- 12 Tplus4.0K Warmer world at 4 degrees K above pre-industrial temperatures
For a hotfix building on 2.32.5 --> 2.32.6
> feature/ECC-1776 GRIB2: Additional activity and experiment table entries for DestinE ClimateDT

- src/grib_iterator_class_healpix.cc
- tests/grib_grid_healpix.sh
- tools/grib_check_gaussian_grid.cc
https://jira.ecmwf.int/browse/ECC-1784
> ECC-1784 GRIB: HealPix Geoiterator: Support nested ordering

- definitions/bufr/section.3.def
- src/bufr_util.cc
- src/grib_index.cc
- tests/CMakeLists.txt
- tests/bufr_ecc-1785.sh
- tests/bufr_extract_headers.sh
https://jira.ecmwf.int/browse/ECC-1785
> ECC-1785: BUFR: Allow encoding satelliteID when rdbType=30

- definitions/mars/grib.mmsf.an.def
https://jira.ecmwf.int/browse/ECC-1821
> ECC-1821: Add mars directives in grib.mmsf.an.def for cerise dataset

- src/grib_handle.cc
https://jira.ecmwf.int/browse/ECC-782
> ECC-782: Multi-field GRIB: crash in grib_handle_new_from_file_multi

- src/accessor/grib_accessor_class_concept.cc
https://jira.ecmwf.int/browse/ECC-1905
> ECC-1905: GRIB: Speed up getting shortName/paramId

- definitions/grib1/local/ecmf/3.table
- definitions/grib1/section.1.def
- definitions/grib1/typeOfLevel.def
https://jira.ecmwf.int/browse/ECC-1908
> abstract single/multiple levels added for GRIB1

- definitions/grib1/local/ecmf/3.table
- definitions/grib1/section.1.def
- definitions/grib1/typeOfLevel.def
https://jira.ecmwf.int/browse/ECC-1908
> ECC-1908: abstract single/multiple levels added for GRIB1

- definitions/grib2/templates/template.4.statistical.def
- tests/grib_step.sh
https://jira.ecmwf.int/browse/ECC-1912
> ECC-1912: GRIB2: Generalise stepType and typeOfTimeIncrement implementation

- definitions/mars/grib.mmsa.em.def
- definitions/mars/grib.mmsa.fcmean.def
- definitions/mars/grib.mmsf.an.def
- definitions/mars/grib.mmsf.fc.def
- definitions/mars/grib.msmm.em.def
- definitions/mars/grib.msmm.fcmax.def
- definitions/mars/grib.msmm.fcmean.def
- definitions/mars/grib.msmm.fcmin.def
- definitions/mars/grib.msmm.fcstdev.def
- definitions/mars/grib.msmm.hcmean.def
Please merge this branch into develop. It contains an addition for centre cmcc for the cerise project.
https://jira.ecmwf.int/browse/ECC-1915
> ECC-1915: Feature/cerise cmcc

- definitions/mars/grib.oper.ep.def
Please merge this branch to hot fix 2.38.2 and develop.
https://jira.ecmwf.int/browse/ECC-1937
> ECC-1937: add ensemble probabilities for AIFS

- definitions/mars/grib.olda.tpa.def
ready to be merged
https://jira.ecmwf.int/browse/ECC-1940
> ECC-1940 adding grib.olda.tpa.def

- definitions/grib2/localConcepts/era6/marsLevtypeConcept.def
- definitions/grib2/localConcepts/era6/typeOfLevelConcept.def
Please merge this branch into develop. For further information, please see ECC-2007.
> ECC-2007: GRIB2: abstract level for ERA6

- src/geo/GeoIterator.cc
- src/geo/GeoIterator.h
- src/geo/iterator/grib_iterator.cc
> eckit::geo

- .github/workflows/build-wheel-macos.yml
- python_wrapper/post-build.sh
- python_wrapper/pre-compile.sh
Adding an action for python wheels on macos, similar to the one on linux
> Python wheel: add macos action

- definitions/grib2/localConcepts/ecmf/modelNameConcept.def
- definitions/grib2/localConcepts/ecmf/modelVersionConcept.aifs-ens-crps.def
- definitions/grib2/localConcepts/ecmf/modelVersionConcept.aifs-ens.def
- definitions/grib2/localConcepts/ecmf/modelVersionConcept.aifs-single-mse.def
- definitions/grib2/localConcepts/ecmf/modelVersionConcept.aifs-single.def
- tests/grib_modelName.sh
https://jira.ecmwf.int/browse/ECC-2027
> ECC-2027: GRIB2: rework the modelName/modelVersion concepts in the context of AIFS

- src/eccodes/accessor/SectionPointer.cc
- src/eccodes/action/Section.cc
- src/eccodes/grib_handle.cc
- src/eccodes/grib_util.cc
- tests/grib_clone_headers_only.cc
- tests/grib_clone_headers_only.sh
- tests/grib_ecc-2045.cc
https://jira.ecmwf.int/browse/ECC-2049
> ECC-2049: GRIB: Problems with clone headers_only after edition conversion

- definitions/grib2/local.crra.3.def
> Update local.crra.3.def with marsKlass

- definitions/grib2/crra_ci_suiteName.table
- definitions/grib2/local.crra.3.def
need to create a local eccodes test with new rr origins
See https://jira.ecmwf.int/browse/ECC-2067
> ECC-2067: GRIB: CARRA/CERRA reanalysis on limited area in the frame of CERISE

- definitions/mars/class.table
https://jira.ecmwf.int/browse/ECC-2076
> ECC-2076: MARS: New class A5 for ECMWF Atmospheric Composition reanalysis version 5 (EAC5)

- src/eccodes/accessor/OffsetValues.cc
- src/eccodes/accessor/ScaleValues.cc
- tests/grib_statistics.sh
https://jira.ecmwf.int/browse/ECC-2083
> ECC-2083: GRIB: Applying the scaleValuesBy operation can produce constant fields

- .github/ci-config.yml
- definitions/grib2/cfVarName.def
- definitions/grib2/localConcepts/ecmf/name.def
- definitions/grib2/localConcepts/ecmf/name.legacy.def
- definitions/grib2/localConcepts/ecmf/paramId.def
- definitions/grib2/localConcepts/ecmf/paramId.legacy.def
- definitions/grib2/localConcepts/ecmf/shortName.def
- definitions/grib2/localConcepts/ecmf/shortName.legacy.def
- definitions/grib2/localConcepts/ecmf/units.def
- definitions/grib2/localConcepts/ecmf/units.legacy.def
- definitions/grib2/name.def
- definitions/grib2/paramId.def
- definitions/grib2/shortName.def
- definitions/grib2/units.def
Hotfix for proper WMO encoding for probabilities
By opening this pull request, I affirm the following:
* All authors agree to the [Contributor License Agreement](https://github.com/ecmwf/codex/blob/main/Legal/contributor_license_agreement.md).
* The code follows the project's coding standards.
* I have performed self-review and added comments where needed.
* I have added or updated tests to verify that my changes are effective and functional.
* I have run all existing tests and confirmed they pass.
> Hotfix 2.39.5

- src/eccodes/accessor/DataCcsdsPacking.cc
- tests/grib_ccsds.sh
This PR adds support for optimizeScaleFactor to CCSDS, implementing the functionality in the same way as for Simple Packing.
> ECC-2088: Add optimizeScaleFactor support to CCSDS

- src/eccodes/geo/BasicAngle.h
- src/eccodes/geo/GribToSpec.cc
Portability fixes
By opening this pull request, I affirm the following:
* All authors agree to the [Contributor License Agreement](https://github.com/ecmwf/codex/blob/main/Legal/contributor_license_agreement.md).
* The code follows the project's coding standards.
* I have performed self-review and added comments where needed.
* I have added or updated tests to verify that my changes are effective and functional.
* I have run all existing tests and confirmed they pass.
> GribFromSpec portability fixes

- src/eccodes/accessor/Time.cc
- src/eccodes/codes_util.cc
- src/eccodes/eccodes_prototypes.h
Ensure that the time values are within the boundaries.
> Check time for validity

- definitions/grib2/products_crra.def
- tests/grib_uerra.sh
See https://jira.ecmwf.int/browse/ECC-1913
By opening this pull request, I affirm the following:
* All authors agree to the [Contributor License Agreement](https://github.com/ecmwf/codex/blob/main/Legal/contributor_license_agreement.md).
* The code follows the project's coding standards.
* I have performed self-review and added comments where needed.
* I have added or updated tests to verify that my changes are effective and functional.
* I have run all existing tests and confirmed they pass.
> ECC-1913: GRIB: Ensemble mean and spread for class=rr in MARS

- tests/CMakeLists.txt
- tools/CMakeLists.txt
See https://jira.ecmwf.int/browse/ECC-2145
By opening this pull request, I affirm the following:
* All authors agree to the [Contributor License Agreement](https://github.com/ecmwf/codex/blob/main/Legal/contributor_license_agreement.md).
* The code follows the project's coding standards.
* I have performed self-review and added comments where needed.
* I have added or updated tests to verify that my changes are effective and functional.
* I have run all existing tests and confirmed they pass.
> ECC-2145: Installation of METAR tools should by default be OFF
