cmake/eccodes_find_linux_utils.cmake

We require a handful of standard linux utils to run the tests - these
need to be explicitly installed on Windows. We add a check for the utils
so we can notify the user if any util is missing.

ECC-852: Add eccodes_find_linux_utils.cmake

---

.appveyor.yml

Now the dtip-windows changes are in the develop branch of ecbuild, we can use develop for the ecCodes CI. Then I can delete the dtip-windows ecbuild branch.

Appveyor: switch to develop branch of ecbuild

---

.travis.yml
README.md

This is currently a basic CI setup. We only build with gcc5.
There are existing ECMWF projects (e.g. https://github.com/ecmwf/atlas/) which build with clang, gcc5, and gcc7. Would we like to do the same for ecCodes? @StephanSiemen @shahramn

Linux: add CI build

---

tests/bufr_ecc-875.sh

Thanks to @shahramn for the fix

MacOS: fix failing test

---

.appveyor.yml
CMakeLists.txt

This should help with relocatability: instead of generating
eccodes-config.cmake with an absolute path to Third Party Libraries
(TPLs) (e.g. /lib/x86_64-linux-gnu/libm.so.6) we have the option to use
the library name instead (e.g. -lm).
We also use library names in eccodes-targets.cmake and eccodes.pc if the
option is set.
The motivation is so that we can distribute packages with conda-forge.
Without this change, the conda-forge build leaves its build path in the
files above. When we come to build another package downstream, e.g.
Magics, we are unable to find the ecCodes libraries because the absolute
paths to the TPLs are no longer valid. Using library names instead lets
cmake find the TPLs on the downstream build system.

Add option to replace TPL absolute paths with library names

---

tests/codes_split_file.sh
tools/codes_split_file.c

Allow an input file to be split into each individual message (if nchunk=-1)

Improvement on file spliting

---

src/grib_expression.c

It seems grib_arguments::expression can be null.
Call stack leading to the crash is as follow. (grib_context.c is modified outside of this pull request. So line numbers may not match there.)
grib_dump -O /home/suzuki/src/eccodes-orig/build/share/eccodes/samples/reduced_gg_pl_48_grib2.tmpl
==673984== Process terminating with default action of signal 11 (SIGSEGV)
==673984==  Access not within mapped region at address 0x0
==673984==    at 0x4A6B42E: grib_expression_free (grib_expression.c:92)
==673984==    by 0x4A6B7AB: grib_arguments_free (grib_expression.c:162)
==673984==    by 0x4A6B794: grib_arguments_free (grib_expression.c:161)
==673984==    by 0x4A6B794: grib_arguments_free (grib_expression.c:161)
==673984==    by 0x4A6B794: grib_arguments_free (grib_expression.c:161)
==673984==    by …

Avoid null pointer dereference in grib_expression_free().

---

src/action_class_transient_darray.c

Freeing of these memory blocks are taken care of in destroy()@action_class_gen.c, aren't they?
Running "codes_parser /home/suzuki/src/eccodes-orig/build/share/eccodes/definitions/bufr/boot.def" complains about 'double free' and dumps core when I call grib_context_reset() on the default context via shared object detachment hook.

Avoid freeing base class members in a derived class.

---

src/action_class_concept.c

Pointers to concept_value in the trie are borrowed pointers, which should not be free'd.)

Fix multiple free in destroy@action_class_concept.c

---

src/grib_accessor_class_data_g2bifourier_packing.c
tests/grib_lam_bf.c

This branch demonstrate that laplam (biFourier encoding) is now broken and suggests a correction.

Fix broken laplam

---

src/grib_api_internal.h

This problem was found and a fix was proposed by Mamoru TASAKA <mtasaka@fedoraproject.org> who deserves full credit for this, to fix test problems on the big endian s390x platform.

add patch to src/grib_api_internal.h

---

src/grib_util.cc

This change is sufficient to post-process an input gridType=lambert to an output of the same gridType, via codes_util_set_spec. This allows transparent support for cropping these grids.

grib_util_set_spec: gridType=lambert

---

.github/ci-nightly-test.sh
.github/workflows/nightly.yml
.github/workflows/reusable-ci-hpc.yml

Adds a github actions workflow and a script to trigger nightly long running tests.
Tests run at 20:00 UTC every day on the develop branch or can be manually dispatched.

Run nightly tests

---

.github/workflows/reusable-ci-hpc.yml

Fixes build-package-hpc inputs for regular CI. Caused by optional inputs for nightly tests which produce invalid yaml file when running the regular CI.

Fix HPC CI build inputs

---

definitions/common/c-1.table
definitions/common/c-11.table
definitions/grib2/local/2.0.table
definitions/grib3/centre.table
definitions/grib3/local/2.0.table
src/bufr_util.cc

Minor change to add abbreviation for Reykjavík Iceland, i.e. birk instead of 213.
This is helpful for some downstream applications at Icelandic Met. Office.

Add abbreviation birk for Reykjavik

---

.github/workflows/reusable-ci-hpc.yml

Enables extended tests for CI running on HPC using the `-DENABLE_EXTRA_TESTS=1` build option.

Enable extended tests in HPC CI

---

.github/workflows/nightly.yml

This allows us to correctly check the previous conclusion of the nightly CI so we can send a notification if previously-failing CI is now passing.
The default workflow_id is `ci.yml` so we've been checking the conclusion of the wrong workflow.

Fix workflow_id for notifications about nightly CI

---

.github/workflows/cd.yml

Adds WF to build and deploy eccodes binary to nexus repository on tag creation.

Add deploy WF

---

.github/workflows/cd.yml

Tags starting with a letter, usually used for experimentation won't trigger CD.

CD: ignore tags starting with a letter

---

.github/workflows/nightly.yml

Adds macos tests to the nightly CI. Macos is only added to the nightly as we have just a few machines right now.
Tests on both intel and m2 architectures.

Add macos nightly CI

---

cmake/FindAEC.cmake

Since CMake 3.12 it is accustomed that find_package can also receive hints from the [`<PackageName>_ROOT`](https://cmake.org/cmake/help/latest/variable/PackageName_ROOT.html#variable:%3CPackageName%3E_ROOT) variable.
This PR adds support for this variable within FindAEC. The cmake package name should be libaec as that is how the package normally advertises itself if config mode were to be used.
This means that a libaec module can now set "export libaec_ROOT=..."
This PR is harmless, just adding extra search hints.

Add libaec_ROOT as search hint for FindAEC

---

.github/ci-nightly-test.sh

Fixes nightly ci script to include a version in the install path.
Test nightly run: https://github.com/ecmwf/eccodes/actions/runs/7165520431/job/19507636503

Add version to nightly ci install path

---

src/grib_accessor_class_g2end_step.cc
src/grib_accessor_class_step_in_units.cc
tests/grib_sub_hourly.sh

Default native step type is string. It's long if unit is not shown.

---

src/step_unit.cc
src/step_unit.h

This fix resolves the problem with the initialisation of static members when compiling ecCodes with the -DBUILD_SHARED_LIBS=*OFF* flag.

ECC-1771: Fix step units initialisation in static library

---

definitions/mars/grib.mmsf.fc.def
definitions/mars/grib.msmm.fcmean.def

we neeed to merge this for the next hotfix version. 
The branch contains the necessary changes to add the MARS keyword "system" for class cerise (class=ci) and stream type combination mmsf/gc and msmm/fcmean

ECC-1774 adding MARS system keyword for mmsf/fc and msmm/fcmean

---

definitions/grib2/post_meta_data.hook.products_12.def
tests/grib_ecc-1691.sh

Development so that stepRange is used to index temporally processed fields rather than endStep. This is an important addition which means that two temporally processed fields over different time ranges can be distinguished and won't overwrite each other when written to the fdb or archived.
ClimateDT uses date and time to index and not step, so we apply this change to all other datasets.
See https://jira.ecmwf.int/browse/ECC-1796

ECC-1796: Implement stepRange indexing for DestinE ExtremesDT and On-Demand ExtremesDT data

---

definitions/grib1/localConcepts/ecmf/paramIdForConversion.def
definitions/grib1/localConcepts/ecmf/stepTypeForConversion.def
definitions/grib1/paramIdForConversion.def
definitions/grib1/section.1.def
definitions/grib2/boot.def
src/grib_accessor_class_concept.cc
tests/CMakeLists.txt
tests/grib_ecc-1806.sh

https://jira.ecmwf.int/browse/ECC-1806

https://jira.ecmwf.int/browse/ECC-1806

---

.github/workflows/ci.yml

Run code coverage on self-hosted runners instead of cloud runners.

Run codecov on self hosted runners

---

src/grib_accessor_class_g2end_step.cc
src/grib_accessor_class_optimal_step_units.cc
tests/grib_sub_hourly.sh

https://jira.ecmwf.int/browse/ECC-1813

ECC-1813: Setting stepunits has no effect

---

.github/workflows/ci.yml

The notify step was skipped on failing jobs because the `always()` was not handled properly. Instead of `always() && ${{ ... }}` we have to pull in the always `${{ always() && .. }}`

Update ci.yml to fix notification

---

definitions/grib2/local/ecmf/parameters_extras.def
definitions/grib2/local/ecmf/section4_extras.def
definitions/grib2/localConcepts/ecmf/modelNameConcept.def
definitions/grib2/localConcepts/ecmf/modelVersionConcept_AIFS.def
definitions/grib2/localConcepts/ecmf/modelVersionConcept_IFS.def
definitions/grib2/localConcepts/era6/modelNameConcept.def
definitions/grib2/localConcepts/era6/modelVersionConcept_AIFS.def
definitions/grib2/localConcepts/era6/modelVersionConcept_IFS.def
definitions/grib2/modelNameConcept.def
definitions/grib2/section.4.def
tests/CMakeLists.txt
tests/grib_ecc-1846.sh

https://jira.ecmwf.int/browse/ECC-1846

ECC-1846: GRIB2: Add optional modelName and modelVersion in section 4

---

definitions/grib2/local.98.43.def
tests/grib_ecc-1766.sh

After a discussion with modelling partners at BSC who will also contribute to EERIE it was clear several keys used in the DestinE ClimateDT layout would be useful within the context of the EERIE data layout.
Therefore we will add the keys generation, model and resolution to the EERIE data layout (localTemplateNumber 43), taking the same values as within the ClimateDT.
This has been agreed as an acceptable change with those involved with EERIE given that this will produce better synergies in the future with other datasets and allow the same processing pipelines to be used. Previous GRIB fields with centre 98, local def 43 will have to be DISCARDED.

ECC-1850: Extended metadata keys along with corresponding test

---

tools/bufr_compare_dir

`bufr_compare_dir` is the only installed script that requires `ksh`. With minor changes it is possible to make this script compatible with standard POSIX sh.
Removing the need to use `ksh` greatly simplifies many aspects of the efforts needed to package, install and maintain eccodes in distributions like Debian.
See: https://bugs.debian.org/1078095

tools/bufs_compare_dir: Make compatible with POSIX sh

---

CMakeLists.txt

This patch makes possible to clone and build this repo without additional download steps

Fetch ecbuild if not downloaded before

---

definitions/mars/grib.mmsf.an.def

Please merge this change into develop. It is needed as step must be also for type=an in the mars namespace as the mars client compares this key before archiving data.
https://jira.ecmwf.int/browse/ECC-1953

ECC-1953: leave step in mars namespace for mmsf/an data

---

src/action_class_alias.cc
tests/CMakeLists.txt
tests/grib_ecc-1898.sh
tests/grib_uerra.sh

https://jira.ecmwf.int/browse/ECC-1898

ECC-1898 GRIB: Key 'levelist' persists despite being taken out of the mars namespace

---

definitions/grib1/section.1.def
tests/grib1to2.sh

https://jira.ecmwf.int/browse/ECC-1954

ECC-1954: GRIB1 to GRIB2 conversion does not preserve ensemble product template for some statistically processed fields

---

src/eccodes_prototypes.h
src/grib_api_internal.h
src/grib_filepool.cc
src/grib_index.cc

Keep a reference counter on `grib_files` in the `file_pool` static (global) object. Then store a clone of this object in the `grib_index` structs and keep a pointer to the original object. Every time the index objects are destroyed, decrease the reference counters in the pool, if it ever reaches zero, immediately remove the file from the pool as well.
This was causing serious issues in our live system after a few days of no downtime because of the linear searches we do in the pool to avoid opening the same file more than once.
See https://jira.ecmwf.int/browse/DSC-30265

Remove grib_file from file_pool if no more grib_index holds it

---

src/accessor/grib_accessor_class_data_g22order_packing.cc
src/action_class_when.cc
tests/grib_bitmap.sh

https://jira.ecmwf.int/browse/ECC-1968

ECC-1968: GRIB2 grid_complex_spatial_differencing: Encoding with bitsPerValue=24 fails

---

definitions/mars/class.table

https://jira.ecmwf.int/browse/DGOV-513
https://jira.ecmwf.int/browse/ECC-2004

ECC-2004: MARS: Add new class 'lr' for WMO Lead Centre for Global Climate Re-Analyses

---

definitions/grib2/local/ecmf/section4_extras.def

This is needed for class ml where we do not wanrt the model keyword in the mars namespace

remove the model keyword from the MARS namespace for class ml

---

src/eccodes/grib_util.cc
tests/grib_util_set_spec2.cc

I'm trying to encode a lambert conformal conic grid (gridType=lambert) in eccodes, and generally, I can without an issue for GRIB edition=1.
But it seems to fail for GRIB edition=2, on the account that I'm trying to encode a negative value for longitudeOfFirstGridPoint (and likely, for the last grid point too). Note that this has always worked before, for grids other than gridType=lambert (regular_ll, reduced_gg, the classics). 
Internally, it looks like so:
mars - DEBUG  - 20250312.115307 - ###################################################################################
mars - DEBUG  - 20250312.115307 - Save[packing=simple,output=GribMemoryOutput[]]
mars - DEBUG  - 20250312.115307 - ###################################################################################
mars - DEBUG  - …

Feature/grid type=lambert,edition=2

---

definitions/grib2/typeOfLevelConcept.def

This PR is related to JIRA ECC-2048 in which new stratospheric and tropospheric parameters are requested.
The branch adds two new typeOfLevel entries for stratosphere and troposphere.
Please merge it into develop.

stratosphere and troposphere added to typeOfLevel

---

definitions/grib2/typeOfLevelConcept.def

Added for low- and high cloud layers concepts with the svals / sfacs explicitly set to missing.
Please merge into develop.

GRIB: sval/sfac keys explicitly set to missing for low and high cloud layers

---

python_wrapper/buildconfig

As explained in the code comment, we declare fckit dependency as the easiest means to bring in the intel fortran libraries

Py Wheel: Add fckit dependency

---

python_wrapper/buildconfig

Adding eckit as a wheel dependency, to overcome dependency resolution issues
Note this does *not* add code dependency for eccodes on eckit

Py wheel: explicit dependency order

---

src/eccodes/grib_jasper_encoding.cc
tests/grib_encode_pthreads2.sh

This MR relates to SID-110476 in the ECMWF Jira.
A couple of years ago it looks like ECMWF discovered that parallel JPEG encode using Jasper didn't work - 
https://github.com/ecmwf/eccodes/commit/a950ca130cf1d122e2685c1057bc5b67d088d0bd
However, there was a way to make it thread safe, as it was only the initialisation and cleanup that had issues - or perhaps Jasper has improved since then. I do not have a way to test with old versions of Jasper to confirm, but I would also be surprised if someone is using the HEAD of eccodes and very old versions of Jasper.
I personally used the little program below for testing, but then noticed today that there was a test built into eccodes that should handle it too.
```c
#include <omp.h>
#include <stdio.h>
#include <stdlib.h>
#include "eccodes.h"
int …
```

Allow Jasper encode/decode to run in parallel
